---
grails:
    profile: web
    codegen:
        defaultPackage: another
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
management:
    endpoints:
        enabled-by-default: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none

---
hibernate:
    allow_update_outside_transaction: true
    order_inserts: true
    order_updates: true
    #  flush:
    #    mode: org.grails.orm.hibernate.COMMIT
    #  generate_statistics: true
    #only for sql server
    #    default_schema: dbo
    #    hbm2ddl:
    #        jdbc_metadata_extraction_strategy: individually
    #  naming_strategy: com.twc.fatcaone3.CustomNamingStrategy
    jdbc:
        use_get_generated_keys: true
        batch_size: 20
        batch_versioned_data: true
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
        provider_class: net.sf.ehcache.hibernate.EhCacheProvider
        region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    dialect: org.hibernate.dialect.SQLServer2012Dialect
    #  driverClassName: com.mysql.cj.jdbc.Driver
    #  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    username: miguel
    password: 'welcome1'
#  username: root
#  password: 'P@$$w0rd123.'
environments:
    development:
        dataSource:
            dbCreate: none
            #      logSql: true
            url: jdbc:sqlserver://localhost;databaseName=prueba;useUnicode=true;characterEncoding=UTF-8;sendStringParametersAsUnicode=false;prepareSQL=1
    #              url: jdbc:sqlserver://100.27.20.181;databaseName=twcPrueba;useUnicode=true;characterEncoding=UTF-8
    test:
        dataSource:
            dbCreate: none
            #            url: jdbc:sqlserver://localhost;databaseName=twcPrueba
            url: jdbc:sqlserver://localhost;databaseName=prueba;useUnicode=true;characterEncoding=UTF-8;sendStringParametersAsUnicode=false;prepareSQL=1
    production:
        dataSource:
            dbCreate: none
            url: jdbc:sqlserver://localhost;databaseName=prueba;useUnicode=true;characterEncoding=UTF-8;sendStringParametersAsUnicode=false;prepareSQL=1
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
grails:
    plugin:
        databasemigration:
            updateOnStart: true
            updateOnStartFileName: changelog.groovy
